### ISSUE TITLE
Web-App-Starter behaving weird.

### ISSUE THREAD

**Issue by siripuramrj** [PredixDev/predix-webapp-starter#16] opened 2017-08-25 10:14 UTC
I make some minor changes in the Web-App-Starter app then do a
  ~gulp dist
  ~gulp //works successfully in local machine
  ~cf push //does not work properly on cloud.
In my local env I get output successfully like this
![workingin local](https://user-images.githubusercontent.com/31343401/29709956-0f7a5a70-89ac-11e7-985f-0b4b773b08a4.PNG)
but in cloud it does not work
Please Check(https://gcc-app-test.run.aws-usw02-pr.ice.predix.io/#/rmd)

**Comment by gstroup** [comment] 2017-08-25 15:54
I see lots of 404 errors in the cloud.  Looks like there are missing components.  Please make sure the bower install was successful.  And you may need to modify the polymer.json file depending on the changes you made to the app.  You can also run `gulp --dist` to test locally from the dist directory.

**Comment by siripuramrj** [comment] 2017-09-07 18:51
Thank you, this is the perfect command for testing before pushing to cloud, works great..

**Comment by gstroup** [comment] 2017-09-14 22:41
Closing this issue, since we can't reproduce.  Please get the latest version, and if you see more problems, open a new issue.  Thank you.

**Closed by gstroup** 2017-09-14 22:41 UTC
